spring.application.name=api-produtos

# Configurar a conexão do banco de dados com o spring boot

# JDBC é o protocolo padrão do Java pra falar com bancos relacionais; localhost:3306 é o endereço+porta padrão do MySQL; e no final entra o nome do banco que você criou
spring.datasource.url=jdbc:mysql://localhost:3306/api_produtos
spring.datasource.username=root
spring.datasource.password=lauriana1
spring.jpa.hibernate.ddl-auto=update
# Para mostrar o resultado do hibernate no terminal
spring.jpa.show-sql=true